# vim: syntax=yaml

# tail /var/log/cloud-init-output.log 

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - zsh
  - build-essential # GCC/Make
  - cmake
  - htop
  - neofetch
snap:
  commands:
    00: snap install btop

users:
  - name: chafey
    gecos: Chris Hafey
    groups: adm, systemd-journal, sudo, netdev, lxd, staff
    expiredate: '2032-09-01'
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys: 
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQAXMT9OmodpLiSGe6ThudrMGiUCEdRNXY1DEnCbXc8Fm+Mtzm1EPRthmbcmW2BcjwRHjHGwAbUf9u5u0jsEJ3ynnWM5xu8BNeBchovKo6/V/T/6Sa5+wclfgzF4dB6dhAv+Rh7AAye4Udt6VggRhwEGLA3SZi2CRUzq31B2vbPi15ogBLI0n+PKi/jgNlWAlPgB17xZJV+j1tGMFANxxfvbbAlVcLNssW0B0RycUsCwFuy3Pbj+1zGLYXuU2hGob6AlWShIv4tDfBOAv4yKrxreKRK/PbPF6LEJy9KQe2aWqB6j6//2yK2XC5R5j6AmVRLjMjxHF/aSNNhQn+xRMak11JS8CUd/DQkgnTRTWqrVCoIQBZm4als1oL6p2V6q/JbC9Wl71XDH6wVMq2qndVhHYymoJSQcbXkFg/WeEzvw0qTVxkyZ9zQc6E8THw+qUDRgdqKksid+55cfeb2uPqzeUiqnLXRfffkDPLfIbH2DZU3MT4QWVn+Hk/0oem2WU= chafey@Chriss-MBP-2"
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB/JbMwXMVASucINHTCllDqWyS5hoGZYnjg2n8kooFMN15spmO90te6RPw4lHDGwcUDTgsK1doMp2yr9rxeLDxY="

write_files:
- path: /lib/systemd/system/code-server.service
  content: |
    [Unit]
    Description=code-server
    After=network.target

    [Service]
    Type=simple
    User=chafey
    Group=chafey
    WorkingDirectory = /home/chafey
    Environment="PATH=/home/chafey:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    ExecStart=/usr/bin/code-server --bind-addr 0.0.0.0:8080 --auth none
    Restart=always

    [Install]
    WantedBy=multi-user.target
  owner: 'root:root'
  permissions: '0640'
  defer: true
- path : /home/chafey/.gitconfig
  content: |
    [init]
      defaultBranch = main
    [user]
      name = Chris Hafey
      email = chafey@gmail.com
  owner: 'chafey:chafey'
  permissions: '0664'
  defer: true
runcmd:
 - [su, chafey, -c, "/usr/bin/curl -fsSL https://code-server.dev/install.sh | sh"]
 - [su, chafey, -c, "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash"]
 - [su, chafey, -c, "export NVM_DIR=\"$HOME/.nvm\"; [ -s \"$NVM_DIR/nvm.sh\" ];  \\. \"$NVM_DIR/nvm.sh\"; nvm install node"]
 - [systemctl, daemon-reload]
 - [systemctl, start, code-server]
 - [systemctl, enable, code-server]
